### ISSUE TITLE
Negative Values

### ISSUE THREAD

**Issue by GniLudio** [Nibuja05/dota_ability_transformer#3]
# Negative Values

Why are negative values not converted?

## TypeScript
```typescript
    SpecialValues: AbilitySpecials = {
        slow: -25.0,
        attack_speed: [100, -200, 300, -400]
    }
```

## KeyValues
```
        "AbilitySpecial"
        {
            "01"
            {
                "var_type"    "FIELD_INTEGER"
                "attack_speed"    "100 300"
            }
        }
```

## Annotation
Since dota integer tooltips can't display negative values,
if you fix negative values, they should always be float type.

**Comment by Nibuja05** [comment]
Closed in [this commit](https://github.com/Nibuja05/dota_ability_transformer/commit/16f006f1ea5c7d9e79dd5476bfc4ce3c346611d6)
