### ISSUE TITLE
Ability types missing `DOTA_`

### ISSUE THREAD

**Issue by GniLudio** [Nibuja05/dota_ability_transformer#4]
The ability types are missing `DOTA_` at the start in the key values.

Currently 
`Type: AbilityTypes.ULTIMATE` 
is converted to 
`"AbilityType"    "ABILITY_TYPE_ULTIMATE"`

But the correct value is `DOTA_ABILITY_TYPE_ULTIMATE`.

**Comment by Nibuja05** [comment]
Closed in [this commit](https://github.com/Nibuja05/dota_ability_transformer/commit/16f006f1ea5c7d9e79dd5476bfc4ce3c346611d6)
